name: test_on_PR

on:
    pull_request:
        branches: [master]

jobs:
    lint_and_test:
        uses: ./.github/workflows/test_reusable_workflow.yml
        with:
            python-version: "3.11"
            os: "windows-latest"
        secrets: inherit
